processors:
  batch:

exporters:
  logging:
    loglevel: "debug"

  jaeger:
    #endpoint: jaeger-all-in-one:14250
    endpoint: 0.0.0.0:14250
    tls:
      insecure: true

receivers:
  otlp:
    protocols:
      grpc:

  solace:
    broker: [localhost:5672]
    max_unacknowledged: 500
    auth:
      sasl_plain:
        username: trace
        password: trace
    queue: queue://#telemetry-trace
    tls:
      insecure: true
      insecure_skip_verify: true


service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [solace,otlp]
      processors: [batch]
      exporters: [jaeger,logging]
